<template lang="pug">
  .service-worker
    h1.title I'm a service worker, I can work off line
    p.devider  ------------------------------------------------------- Notification -------------------------------------------------------
    el-button.request-notification-btn(@click="handleRequestNotifyPermission") Request Notify Permission
    el-button.notification-btn(@click="handleNotify") Notify
    p.devider -------------------------------------------------- Push Notification --------------------------------------------------
    p.desc 由于push消息会经过浏览器的server, 目前chrome只能翻墙才能接收到: http://www.zhengqingxin.com/post/push-knock-the-door.html
    el-button.subscribe-push-btn(@click="handleSubcribePush") Subscribe Push
    el-button.push-btn(@click="handlePush") Push
    p.desc for testing purposes, in actual applications the push notification is likely going to be generated by some event in the server)
</template>

<script>

  import {urlBase64ToUint8Array} from './tools'

  export default {
    name: 'service-worker',
    components: {},
    data () {
      return {
        subscription: null
      }
    },
    beforeCreate () {
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', function() {
          navigator.serviceWorker.register('/service-worker/sw.js').then(
            function(registration) {
              // Registration was successful
              console.log('ServiceWorker registration successful with scope: ', registration.scope);
            }
          ).catch(
            function(err) {
              // registration failed :(
              console.log('ServiceWorker registration failed: ', err);
            }
          );

        });
      }
    },
    mounted () {
    },
    methods: {
      handlePush () {
        // Ask the server to send the client a notification (for testing purposes, in actual
        // applications the push notification is likely going to be generated by some event
        // in the server).
        fetch('/service-worker/sendNotification', {
          method: 'post',
          headers: {
            'Content-type': 'application/json'
          },
          body: JSON.stringify({
            subscription: this.subscription,
            delay: 0,
            ttl: 0,
          }),
        });
      },
      handleSubcribePush() {
        if ('serviceWorker' in navigator) {
          navigator.serviceWorker.ready.then(registration => {
            // Use the PushManager to get the user's subscription to the push service.
            return registration.pushManager.getSubscription()
            .then(async subscription => {
              // If a subscription was found, return it.
              if (subscription) {
                return subscription;
              }

              // Get the server's public key
              const response = await fetch('./vapidPublicKey');
              const vapidPublicKey = await response.text();
              // Chrome doesn't accept the base64-encoded (string) vapidPublicKey yet
              // urlBase64ToUint8Array() is defined in /tools.js
              const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey);

              // Otherwise, subscribe the user (userVisibleOnly allows to specify that we don't plan to
              // send notifications that don't have a visible effect for the user).
              return registration.pushManager.subscribe({
                userVisibleOnly: true,
                applicationServerKey: convertedVapidKey
              });
            });
          }).then(subscription => {
            this.subscription = subscription
            // Send the subscription details to the server using the Fetch API.
            fetch('/service-worker/register', {
              method: 'post',
              headers: {
                'Content-type': 'application/json'
              },
              body: JSON.stringify({
                subscription: subscription
              }),
            });
            console.log('subscription: ' + JSON.stringify(subscription))
          });
        }
      },
      handleRequestNotifyPermission() {
        // It's best practice to call the requestPermission() function in response to a user action signalling
        if ('Notification' in window) {
          Notification.requestPermission(function(status) {
            console.log('Notification permission status:', status);
          });
        }
      },
      handleNotify() {
        if (Notification.permission == 'granted') {
          navigator.serviceWorker.getRegistration().then(function(reg) {
            var options = {
              body: 'Here is a notification body!',
              // icon: 'images/example.png',
              vibrate: [100, 50, 100],
              data: {
                dateOfArrival: Date.now(),
                primaryKey: 1
              },
              actions: [
                {
                  action: 'explore',
                  title: 'Explore this new world',
                  // icon: 'images/checkmark.png'
                },
                {
                  action: 'close',
                  title: 'Close notification',
                  // icon: 'images/xmark.png'
                },
              ]
            };
            reg.showNotification('Hello world!', options);
          });
        }
      }
    }
  }
</script>
